name: clang

on: push

jobs:

  main:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build lld clang-14
          sudo ln -sf /usr/local/bin/ld /usr/bin/lld
      - name: Configure CMake
        run: |
          cmake . -DBUILD_TESTING=ON -B build \
            -G "Ninja"                   \
            -DCMAKE_BUILD_TYPE=Debug     \
            -DCMAKE_C_COMPILER=clang-14     \
            -DCMAKE_CXX_COMPILER=clang++-14 \
      - name: Build
        run:
          cmake --build build
         
      - name: Test
        run: |
          cd build
          ctest --output-on-failure -C Debug -V
          ctest --output-on-failure -C Release -V